version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: reverse-string-huzaifa

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - IMAGE_TAG=${CODEBUILD_BUILD_NUMBER}
      - echo "Building image with tag:${IMAGE_TAG}"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}

  post_build:
    commands:
      - echo "Pushing image to Amazon ECR..."
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - echo "Image pushed successfully."
      - printf '{"ImageURI":"%s"}' ${REPOSITORY_URI}:${IMAGE_TAG} > imageDetail.json

artifacts:
  files:
    - appspec.yml
    - imageDetail.json
    - scripts/**/*